# This is name of the workflow that will be displayed ion Actions tab

name: Sujal

on:
  workflow_dispatch:
    inputs:
      enviromnet:
       description: This is the env value where workflow runs
       default: 'dev'
       required: true
       type: choice
       options:
         - dev
         - prod
         - staging
        

jobs:
  code:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          run: echo "Clone from github"
     
      
  build:
      needs: [code]
      runs-on: ubuntu-latest
      steps: 
        - name : build a code
          run: echo "Build your code here"
  
  test:
      needs: [code,build]
      runs-on: ubuntu-latest
      steps:
        - name: Testing
          run:  echo "Test you code here"
      
  deploy:
      needs: [code,build,test,]
      runs-on: ubuntu-latest
      steps: 
        - name: Deployment
          run: echo "Deploy your code here"
  
  
