# This is workflow name
name: Hello Sujal

# runs on a trigger on:
on:
  push:
    branches: [main]
    paths:
    - '**.html'
    - '**.yml'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say Hello to user
        run: echo "Hello User"
      - name: say Hello to username
        run: echo "Hello $USER" 

  details:
    runs-on: ubuntu-latest
    steps:
      - name : Show what is a version of docker python etc.
        run : docker --version && python --version
  
